const constants = {
    ADD_MESSAGE: "ADD_MESSAGE",
    ADD_MESSAGES: "ADD_MESSAGES",
    TOGGLE_THING: "TOGGLE_THING",
    UPDATE_ALL_THINGS: "UPDATE_ALL_THINGS",
    UPDATE_CONNECTIONS: "UPDATE_CONNECTIONS",
    UPDATE_SYSTEMS: "UPDATE_SYSTEMS",
    UPDATE_SYSTEM: "UPDATE_SYSTEM",
    UPDATE_THINGS: "UPDATE_THINGS",
    THING_ONLINE: "THING_ONLINE",
    THING_OFFLINE: "THING_OFFLINE",
    ITEM_CHANGE_STATE: "ITEM_CHANGE_STATE",
    ITEM_CHANGE_VALUE: "ITEM_CHANGE_VALUE",
    METHOD_CHANGE_STATE: "METHOD_CHANGE_STATE",
    ADD_SYSTEM: "ADD_SYSTEM",
    DELETE_SYSTEM: "DELETE_SYSTEM",
    SIGN_IN: "SIGN_IN",
    SIGN_UP: "SIGN_UP",
    ADD_TOKEN: "ADD_TOKEN",
    QUIT: "QUIT"
}
export default constants